### ISSUE TITLE
TieredRewards isn't working

### ISSUE THREAD

**Issue by HunterZomb** [AerWyn81/HeadBlocks#1]
TieredRewards option isnt working here's my config:

```
tieredRewards:
   10:
    - "cmd: crate givekey %player% epic 1"
```

Version: 1.17.1

Software: Airplane

Java Version: 16

**Comment by AerWyn81** [comment]
Hi,

I'll release a patch within 30 minutes that fixes this problem.
I'll let you close the issue once you've checked the behavior :)

Sorry for the inconvenience,
Thanks for the review and the report! ❤️
