### ISSUE TITLE
Error when placing /hb give

### ISSUE THREAD

**Issue by NyhmsQuest** [AerWyn81/HeadBlocks#13]
I sneak and placed a headblock and the moment it placed I disconnected and I'm now unable to connect to the server.
https://mclo.gs/V2bYOQJ

**Comment by AerWyn81** [comment]
Hi, there's a known issue with the default hologram system and latest MC version. To resolve it, you can :

- Use a plugin to handle holograms (https://aerwyn81.github.io/HeadBlocks/#/config/config?id=holograms)
- Disable the holograms in the config
