### ISSUE TITLE
[Feature request] add CMI Holograms

### ISSUE THREAD

**Issue by Leahcimkrob** [AerWyn81/HeadBlocks#16]
Please add support for CMI holograms.

https://www.zrips.net/cmi/api/

**Comment by AerWyn81** [comment]
Hi, thanks for the suggestion

Added in [5a86d4](https://github.com/AerWyn81/HeadBlocks/commit/5a86d479ebfc65611b3b5585f98ec3a02e03d67a)

I recommend using the plugin's internal holograms (DEFAULT type). I've implemented CMI but it's a bit temperamental.
You can try it with the hologram type : "CMI" in the 2.3.0 release downloadable [here](https://www.spigotmc.org/resources/headblocks-updated-1-16-5-1-20-easter-eggs-multi-server-support-fully-translatable-free.97630/update?update=503925)!

Let me know if it's right for you ;)

**Comment by Leahcimkrob** [comment]
Thank You
