### ISSUE TITLE
Locations not loading on server startup

### ISSUE THREAD

**Issue by HunterZomb** [AerWyn81/HeadBlocks#2]
Head locations aren't loading on server startup, after using /hb reload it loads the head locations

Version: 1.17.1

Software: Airplane

Java Version: 16

**Comment by AerWyn81** [comment]
Hi,

That's strange, do you have any error at server startup log ?

**Comment by AerWyn81** [comment]
Ok, I reproduce the issue. Going to fix that asap, sorry!

**Comment by AerWyn81** [comment]
When the server loading, the world is not necessarily loaded. 
I developed a fix that will solve this issue, I will update the plugin soon ! Thans for your report!

**Comment by AerWyn81** [comment]
Hey,

The plugin has been updated with the fix for your need!
Don't hesitate to come back to me if you have any problem :)

https://www.spigotmc.org/resources/headblocks-1-8-1-17.97630/update?update=432008
